"use client";
import { useEffect, useState, useCallback, useRef } from "react";
import { CloudSun, Wind, Waves, MapPin, RefreshCw, Droplets, Thermometer, Gauge, Sun, Cloud, CloudRain, Moon, Sunrise, Sunset, TriangleAlert, ExternalLink, LayoutDashboard } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { cachedData, refreshData } from "./lib/browser-data";
import AirForecast from "./components/AirForecast";
type Result = { data: any; loading: boolean; error: boolean };
const empty: Result = { data: null, loading: true, error: false };
const number = (v: any, decimals = 0) => v === null || v === undefined || !Number.isFinite(Number(v)) ? "—" : Number(v).toLocaleString("pl-PL", { maximumFractionDigits: decimals });
function localDate(value: string) { return value ? new Intl.DateTimeFormat("pl-PL", { day:"2-digit", month:"2-digit", hour:"2-digit", minute:"2-digit", timeZone:"Europe/Warsaw" }).format(new Date(value)) : "Brak czasu pomiaru"; }
function condition(code: number) { if(code===0)return "Bezchmurnie";if(code<=2)return "Częściowe zachmurzenie";if(code===3)return "Pochmurno";if(code<=48)return "Mgła";if(code<=57)return "Mżawka";if(code<=67)return "Deszcz";if(code<=77)return "Śnieg";if(code<=82)return "Przelotny deszcz";if(code<=86)return "Przelotny śnieg";return "Burza"; }
function WeatherIcon({code,night=false,className=""}:{code:number;night?:boolean;className?:string}) { const Icon=code===0?(night?Moon:Sun):code<=2?CloudSun:code<=48?Cloud:CloudRain;return <Icon className={className} aria-hidden="true"/>; }
function Source({children,href}:{children:React.ReactNode;href:string}) { return <a className="source-link" href={href} target="_blank" rel="noreferrer">{children}<ExternalLink size={12} aria-hidden="true"/></a>; }
function ErrorNote({result}:{result:Result}) { return result.error?<p className="error-note" role="status">Nie udało się pobrać danych.{result.data?" Widoczne są poprzednie odczyty.":" Spróbuj ponownie za chwilę."}</p>:null; }
export default function Dashboard() {
 const [weather,setWeather]=useState<Result>(empty),[air,setAir]=useState<Result>(empty),[water,setWater]=useState<Result>(empty),[alerts,setAlerts]=useState<Result>(empty);
 const refreshing=useRef(false);
 const [checked,setChecked]=useState<string|null>(null),[today,setToday]=useState("");
 const refresh=useCallback(async()=>{if(refreshing.current)return;refreshing.current=true;try{await Promise.all(([["weather",setWeather],["air",setAir],["water",setWater],["warnings",setAlerts]] as const).map(async([type,setter])=>{setter(old=>({...old,data:old.data??cachedData(type),loading:true,error:false}));setter(await refreshData(type));}));setChecked(new Date().toISOString());}finally{refreshing.current=false;}},[]);
 useEffect(()=>{setToday(new Intl.DateTimeFormat("pl-PL",{weekday:"long",day:"numeric",month:"long",year:"numeric",timeZone:"Europe/Warsaw"}).format(new Date()));refresh();const timer=setInterval(refresh,3600000);const resume=()=>{if(document.visibilityState==="visible")refresh();};window.addEventListener("online",refresh);document.addEventListener("visibilitychange",resume);return()=>{clearInterval(timer);window.removeEventListener("online",refresh);document.removeEventListener("visibilitychange",resume);};},[refresh]);

 const loading=weather.loading||air.loading||water.loading||alerts.loading,w=weather.data,a=air.data,h=water.data;
 const weatherOld=Boolean(w&&(w.stale||Date.now()-Date.parse(w.fetchedAt)>3600000||Date.now()-Date.parse(w.current.time)>10800000));
 const forecastToday=new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Warsaw"}).format(new Date());
 const sunIndex=w?.daily.time.indexOf(forecastToday)??-1;
 const clock=(time:string)=>new Intl.DateTimeFormat("pl-PL",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Warsaw"}).format(new Date(time));
 const hours=w?.hourly?.time.map((time:string,i:number)=>({time,i})).filter(({time}:any)=>Date.parse(time)>=Math.floor(Date.now()/3600000)*3600000).slice(0,24)??[];
 const warnings=alerts.data?.warnings.filter((r:any)=>!r.until||Date.parse(r.until)>Date.now())??[];
 const staleAir=a?.indexTime&&Date.now()-new Date(a.indexTime).getTime()>21600000;
 return <><header className="topbar"><div className="topbar-inner"><a href={import.meta.env.BASE_URL} className="brand" aria-label="Szczedrzyk Dash — strona główna"><span className="brand-icon"><LayoutDashboard size={23} aria-hidden="true"/></span><span>Szczedrzyk Dash</span></a><span className="location"><MapPin size={15}/>Gmina Ozimek · Opolskie</span></div></header><main>
 <div className="page-heading"><div><h1>Szczedrzyk Dash</h1><p className="date-line">{today||"Pogoda · Powietrze · Woda"}</p></div><div className="refresh-area"><Button className="refresh-button" variant="outline" onClick={refresh} disabled={loading}><RefreshCw size={16} className={loading?"spin":""}/>{loading?"Pobieranie…":"Odśwież dane"}</Button><span className="checked" aria-live="polite">{checked?`Sprawdzono o ${new Intl.DateTimeFormat("pl-PL",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Warsaw"}).format(new Date(checked))}`:"Łączenie ze źródłami danych"}</span></div></div>
 <section className="card warnings-section" aria-labelledby="warnings-title"><div className="section-heading"><h2 id="warnings-title"><TriangleAlert size={20}/>Ostrzeżenia IMGW</h2><Source href="https://meteo.imgw.pl/">IMGW-PIB</Source></div><p className="section-context">Powiat opolski · zlewnia Małej Panwi</p>{alerts.loading&&!alerts.data?<p>Sprawdzanie ostrzeżeń…</p>:alerts.error?<p className="error-note" role="status">Nie udało się potwierdzić aktualnych ostrzeżeń. Sprawdź komunikaty IMGW; widoczne wcześniejsze ostrzeżenia mogą być nieaktualne.</p>:null}{alerts.data?.failed?.length>0&&<p className="error-note">Nie udało się sprawdzić ostrzeżeń {alerts.data.failed.map((v:string)=>v==="meteo"?"meteorologicznych":"hydrologicznych").join(" i ")}.</p>}{warnings.map((r:any)=><details className={`warning-entry warning-level-${r.level}`} key={r.id}><summary><span><strong>{r.title}</strong><span className="warning-kind">{r.type==="meteo"?"Powiat opolski":"Zlewnia Małej Panwi"} · {Date.parse(r.from)>Date.now()?"Nadchodzące":"Obowiązuje"}</span></span><span className={`pill ${r.level>=3?"danger":"warning"}`}>{r.level>0?`Stopień ${r.level}`:"Komunikat hydrologiczny"}</span></summary><p>{r.description}</p><p className="warning-area">{r.area}</p><p className="warning-validity">Od {localDate(r.from)} · {r.until?`do ${localDate(r.until)}`:"do odwołania"}{r.probability?` · prawdopodobieństwo ${r.probability}%`:""}</p></details>)}{alerts.data&&!alerts.error&&!alerts.data.failed?.length&&!warnings.length&&<p className="no-warnings">Brak aktywnych i nadchodzących ostrzeżeń IMGW dla wskazanego obszaru.</p>}{alerts.data&&<p className="section-meta">Sprawdzono: {localDate(alerts.data.checkedAt)}</p>}</section>
 <section className="card air-card" aria-labelledby="air-title"><div className="card-head"><h2 id="air-title"><Wind size={20}/>Jakość powietrza</h2><span className="pill neutral">POMIAR SYNGEOS</span></div>
 {a?<><p className="station-label"><MapPin size={14}/>{a.station}</p><div className={`air-status ${staleAir?"stale":"aq-"+a.index}`}><span className="status-line">Ocena pyłów PM2,5 i PM10 · skala Syngeos</span><strong>{staleAir?"Nieaktualny indeks":a.label||"Brak indeksu"}</strong></div><div className="aq-scale" aria-hidden="true">{[0,1,2,3,4,5].map(i=><span key={i} className={`scale-${i} ${a.index===i&&!staleAir?"selected":""}`}/>)}</div><div className="aq-scale-labels"><span>Bardzo dobry</span><span>Bardzo zły</span></div><div className="pollutants">{[["PM2,5",a.pm25],["PM10",a.pm10]].map(([label,value]:any)=><div key={label}><span>{label}</span><strong>{number(value?.value,1)} <small>µg/m³</small></strong><span className="pollutant-time">{value?.time?`${localDate(value.time)}${Date.now()-new Date(value.time).getTime()>21600000?" · stary odczyt":""}`:"Brak odczytu"}</span></div>)}</div><p className="card-note">Lokalny czujnik wskazany przez gminę Ozimek. Pomiary orientacyjne; ocena dotyczy pyłów.</p><div className="card-foot"><span>{a.indexTime?`Indeks: ${localDate(a.indexTime)}`:"Brak czasu indeksu"}</span><Source href={"https://panel.syngeos.pl/sensor/pm10?device=10417"}>Syngeos</Source></div></>:<div className="loading-block">{air.loading?<><Skeleton className="h-16 w-full"/><span>Wczytywanie pomiarów ze Szczedrzyka</span></>:<p>Brak dostępnych pomiarów powietrza</p>}</div>}<ErrorNote result={air}/><AirForecast refreshToken={checked}/></section>

 <section className="weather-group" aria-labelledby="weather-group-title"><h2 className="topic-title" id="weather-group-title">Pogoda i prognozy</h2><div className="dashboard-grid"><div className="current-weather-column"><section className="card weather-card" aria-labelledby="weather-title"><div className="card-head"><h3 className="card-title" id="weather-title"><CloudSun size={20}/>Aktualne warunki</h3><span className="pill weather-pill">Szczedrzyk</span></div>
 {w?<><div className="weather-main"><div><div className="big-temperature">{number(w.current.temperature_2m)}<span>°C</span></div><p className="condition">{condition(w.current.weather_code)}</p><p className="feels-like">Odczuwalna {number(w.current.apparent_temperature)}°C</p></div><WeatherIcon code={w.current.weather_code} night={!w.current.is_day} className="main-weather-icon"/></div><div className="weather-metrics"><div><Wind size={18}/><span>Wiatr</span><strong>{number(w.current.wind_speed_10m)} <small>km/h</small></strong></div><div><Droplets size={18}/><span>Wilgotność</span><strong>{number(w.current.relative_humidity_2m)} <small>%</small></strong></div><div><Gauge size={18}/><span>Ciśnienie</span><strong>{number(w.current.pressure_msl)} <small>hPa</small></strong></div></div>{sunIndex>=0&&<div className="sun-times"><div><Sunrise size={19}/><span>Wschód słońca<strong>{clock(w.daily.sunrise[sunIndex])}</strong></span></div><div><Sunset size={19}/><span>Zachód słońca<strong>{clock(w.daily.sunset[sunIndex])}</strong></span></div></div>}<div className="weather-foot"><span>Model pogodowy · {localDate(w.current.time)}{weatherOld?" · starsze dane":""}</span><Source href="https://open-meteo.com/">Open-Meteo</Source></div></>:<div className="loading-block">{weather.loading?<><Skeleton className="weather-skeleton"/><span>Wczytywanie pogody dla Szczedrzyka</span></>:<p>Brak dostępnych danych pogodowych</p>}</div>}{weatherOld||weather.error?<p className="error-note" role="status">{w?"Widoczna jest ostatnia dostępna pogoda. ":"Pogoda chwilowo niedostępna. "}Automatycznie sprawdzam dostępność nowej aktualizacji.</p>:null}</section>
 <section className="card hourly-section" aria-labelledby="hourly-title"><div className="section-heading"><h3 className="card-title" id="hourly-title"><CloudSun size={21}/>Prognoza godzinowa</h3><span className="pill neutral">NAJBLIŻSZE 24 GODZINY</span></div>{hours.length?<><div className="hourly-scroll" tabIndex={0} role="region" aria-label="Prognoza godzinowa — przewiń w poziomie"><table className="hourly-table"><thead><tr><th scope="col">Godzina</th>{hours.map(({time,i}:any)=><th scope="col" key={time}>{clock(time)}<span>{new Intl.DateTimeFormat("pl-PL",{day:"2-digit",month:"2-digit",timeZone:"Europe/Warsaw"}).format(new Date(time))}</span></th>)}</tr></thead><tbody><tr><th scope="row">Pogoda</th>{hours.map(({time,i}:any)=><td key={time} title={condition(w.hourly.weather_code[i])}><span className="sr-only">{condition(w.hourly.weather_code[i])}</span><WeatherIcon code={w.hourly.weather_code[i]} night={!w.hourly.is_day[i]}/></td>)}</tr><tr><th scope="row">Temperatura</th>{hours.map(({time,i}:any)=><td className="hourly-temperature" key={time}>{number(w.hourly.temperature_2m[i])}°C</td>)}</tr><tr><th scope="row">Szansa opadu</th>{hours.map(({time,i}:any)=><td key={time}>{number(w.hourly.precipitation_probability[i])}%</td>)}</tr><tr><th scope="row">Opad</th>{hours.map(({time,i}:any)=><td key={time}>{number(w.hourly.precipitation[i],1)} mm</td>)}</tr><tr><th scope="row">Wiatr</th>{hours.map(({time,i}:any)=><td key={time}>{number(w.hourly.wind_speed_10m[i])} km/h</td>)}</tr></tbody></table></div><p className="section-meta">Przewiń, aby zobaczyć kolejne godziny. Czas polski.{weatherOld?" Widoczne są starsze dane prognozy.":""}</p></>:<div className="hourly-empty">{weather.loading?"Wczytywanie prognozy godzinowej…":"Prognoza godzinowa chwilowo niedostępna."}</div>}</section></div>
 <section className="card forecast-card" aria-labelledby="forecast-title"><div className="card-head"><h3 className="card-title" id="forecast-title"><Thermometer size={20}/>Prognoza na 5 dni</h3><span className="pill neutral">{weatherOld?"STARSZE DANE":"PROGNOZA"}</span></div>{w?<div className="forecast-days">{w.daily.time.map((time:string,i:number)=>({time,i})).filter(({time}:any)=>time>=forecastToday).slice(0,5).map(({time,i}:{time:string;i:number})=><div className="forecast-day" key={time}><div><strong>{time===forecastToday?"Dzisiaj":new Intl.DateTimeFormat("pl-PL",{weekday:"long",timeZone:"Europe/Warsaw"}).format(new Date(time+"T12:00:00Z"))}</strong><span>{time.slice(8,10)}.{time.slice(5,7)}</span></div><WeatherIcon code={w.daily.weather_code[i]}/><div className="forecast-temp"><strong>{number(w.daily.temperature_2m_max[i])}°</strong><span>{number(w.daily.temperature_2m_min[i])}°</span></div><div className="forecast-rain"><Droplets size={13}/>{number(w.daily.precipitation_probability_max[i])}%</div></div>)}</div>:<div className="loading-block">{weather.loading?<Skeleton className="h-36 w-full"/>:<p>Prognoza chwilowo niedostępna</p>}</div>}<div className="card-foot"><span>Temperatura maks. / min. · szansa opadu</span></div></section></div>

 </section>
 <section className="card water-section" aria-labelledby="water-title"><div className="water-heading"><div><h2 id="water-title"><Waves size={21}/>Wody w okolicy</h2><p>Zbiornik Turawa · Mała Panew</p></div><Source href="https://hydro.imgw.pl/">Mapa hydrologiczna IMGW</Source></div>
 {h?<div className="water-grid">{h.reservoir&&<article className="water-station"><div className="water-station-head"><h3>Zbiornik Turawa</h3><span className={`pill ${Date.now()-Date.parse(h.reservoir.time)>86400000?"stale":"neutral"}`}>{Date.now()-Date.parse(h.reservoir.time)>86400000?"Starszy raport":"Raport okresowy"}</span></div><p className="river-label">Jezioro Turawskie · tafla zbiornika</p><div className="water-value">{number(h.reservoir.level,2)} <span>m n.p.m.</span></div><p className="water-caption">Wysokość tafli wody nad poziomem morza</p><p className="station-time">Pomiar: {localDate(h.reservoir.time)} · {new Date(h.reservoir.time).getUTCFullYear()}</p><Source href={h.reservoir.source}>Wody Polskie · raport źródłowy</Source><p className="card-note">Odczyt z ostatniego opublikowanego raportu. Dane nie są pomiarem na żywo.</p>{h.reservoir.unavailable&&<p className="error-note">Nie udało się sprawdzić nowego raportu. Widoczny jest ostatni potwierdzony odczyt.</p>}</article>}{h.riverUnavailable&&<p className="error-note">Wodowskazy IMGW chwilowo niedostępne.</p>}{h.stations.map((s:any)=>{const stale=!s.time||Date.now()-new Date(s.time).getTime()>86400000,alarm=s.level!==null&&s.alarm!==null&&s.level>=s.alarm,warning=s.level!==null&&s.warning!==null&&s.level>=s.warning;return <article className="water-station" key={s.id}><div className="water-station-head"><h3>{s.name==="Turawa"?"Turawa · poniżej zapory":s.name}</h3><span className={`pill ${stale||s.level===null?"stale":alarm?"danger":warning?"warning":"good"}`}>{stale?"Stary odczyt":s.level===null?"Brak odczytu":alarm?"Stan alarmowy":warning?"Stan ostrzegawczy":"Poniżej progów"}</span></div><p className="river-label">{s.river}</p><div className="water-value">{number(s.level)} <span>cm</span></div><p className="water-caption">Stan wody względem zera wodowskazu</p><div className="water-thresholds"><span>Ostrzegawczy <strong>{number(s.warning)} cm</strong></span><span>Alarmowy <strong>{number(s.alarm)} cm</strong></span></div><div className="station-detail"><span>Przepływ: <strong>{number(s.flow,2)} m³/s</strong></span><span className="pollutant-time">{s.flowTime?localDate(s.flowTime):"Brak czasu przepływu"}</span></div><p className="station-time">{s.time?`Pomiar: ${localDate(s.time)}${stale?` · ${new Date(s.time).getUTCFullYear()}`:""}`:"Brak czasu pomiaru"}</p></article>;})}</div>:<div className="loading-block">{water.loading?<><Skeleton className="h-32 w-full"/><span>Wczytywanie wodowskazów w okolicy</span></>:<p>Dane hydrologiczne chwilowo niedostępne</p>}</div>}<ErrorNote result={water}/><div className="water-note"><Waves size={18}/><p><strong>Dwa rodzaje pomiarów:</strong> poziom tafli zbiornika podajemy w m n.p.m., a stany rzeki w cm względem zera każdego wodowskazu. Tych wartości nie należy bezpośrednio porównywać.</p></div></section>
 <footer><div><span className="footer-brand">Szczedrzyk Dash</span><p>Dane pobiera Twoja przeglądarka przy otwarciu strony, co godzinę i po kliknięciu „Odśwież dane”. Ostatnie odczyty zachowuje lokalnie na tym urządzeniu. Czas wyświetlany dla Polski.</p></div><div className="footer-sources"><Source href="https://open-meteo.com/">Open-Meteo</Source><Source href="https://panel.syngeos.pl/sensor/pm10?device=10417">Syngeos</Source><Source href="https://danepubliczne.imgw.pl/">IMGW-PIB</Source><Source href="https://www.gov.pl/web/wody-polskie-gliwice/aktualna-sytuacja-hydrologiczna">Wody Polskie</Source></div><p className="attribution">Kod strony jest publicznie dostępny na portalu GitHub. <Source href="https://github.com/strzelcu/szczedrzyk">Zobacz repozytorium</Source></p><p className="attribution">Dane Instytutu Meteorologii i Gospodarki Wodnej – Państwowego Instytutu Badawczego zostały przetworzone. Dane operacyjne mogą podlegać korektom.</p></footer>
 </main></>;
}
